"""empty message

Revision ID: d64fef262eaa
Revises: 
Create Date: 2022-10-15 13:31:42.449940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64fef262eaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_At', sa.DateTime(), nullable=False),
    sa.Column('updated_At', sa.DateTime(), nullable=True),
    sa.Column('room', sa.String(length=225), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connected',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_At', sa.DateTime(), nullable=False),
    sa.Column('updated_At', sa.DateTime(), nullable=True),
    sa.Column('connected_user_id', sa.Integer(), nullable=False),
    sa.Column('connection_room_id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['connected_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_room_id'], ['room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_At', sa.DateTime(), nullable=False),
    sa.Column('updated_At', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_At', sa.DateTime(), nullable=False),
    sa.Column('updated_At', sa.DateTime(), nullable=True),
    sa.Column('notification_user_id', sa.Integer(), nullable=False),
    sa.Column('notification_message_id', sa.Integer(), nullable=False),
    sa.Column('notification_read', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['notification_message_id'], ['message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'country', ['country_abbrev'])
    op.drop_constraint(None, 'liked', type_='foreignkey')
    op.drop_constraint(None, 'liked', type_='foreignkey')
    op.create_foreign_key(None, 'liked', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'liked', 'activity', ['activity_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'country', ['country_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'liked', type_='foreignkey')
    op.drop_constraint(None, 'liked', type_='foreignkey')
    op.create_foreign_key(None, 'liked', 'activity', ['activity_id'], ['id'])
    op.create_foreign_key(None, 'liked', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_table('notifications')
    op.drop_table('message')
    op.drop_table('connected')
    op.drop_table('room')
    # ### end Alembic commands ###
